In [4]:
import numpy as np
import pandas as pd

In [6]:
df = pd.DataFrame([{'product_id':23, 'name':'computer', 'wholesale_price': 500,
        'retail_price':1000, 'sales':100},
        {'product_id':96, 'name':'Python Workout', 'wholesale_price': 35,
        'retail_price':75, 'sales':1000},
        {'product_id':97, 'name':'Pandas Workout', 'wholesale_price': 35,
        'retail_price':75, 'sales':500},
        {'product_id':15, 'name':'banana', 'wholesale_price': 0.5,
        'retail_price':1, 'sales':200},
        {'product_id':87, 'name':'sandwich', 'wholesale_price': 3,
        'retail_price':5, 'sales':300},
        ])

df.head()

   product_id            name  wholesale_price  retail_price  sales
0          23        computer            500.0          1000    100
1          96  Python Workout             35.0            75   1000
2          97  Pandas Workout             35.0            75    500
3          15          banana              0.5             1    200
4          87        sandwich              3.0             5    300

For what products is the retail price more than twice the wholesale price?

In [9]:
df[df['retail_price'] > df['wholesale_price']*2]

   product_id            name  wholesale_price  retail_price  sales
1          96  Python Workout             35.0            75   1000
2          97  Pandas Workout             35.0            75    500

How much did the store make from food versus computers versus books? (You can retrieve based on the index values, not anything more sophisticated.)

In [10]:
df

   product_id            name  wholesale_price  retail_price  sales
0          23        computer            500.0          1000    100
1          96  Python Workout             35.0            75   1000
2          97  Pandas Workout             35.0            75    500
3          15          banana              0.5             1    200
4          87        sandwich              3.0             5    300

In [23]:
book = df.iloc[1,2]['retail_price']
    #[['retail_price']-['wholesale_price']]
print(computers)

IndexError: invalid index to scalar variable.